iamUser:
  Type: AWS::IAM::User
  Properties:
    Path: /
    Groups:
      - groupname
    LoginProfile:
      Password: 
      PasswordResetRequired: true|false
    Policies:
      - policyname
    ManagedPolicyArns:
      - managedpolicyarn